let firstname= 'Martin'
let surname ='Okonye'
let age = 35
let bill =5000000
let favouritecolor = 'green'
let gender ='male'
let maritalstatus = 'single'
let nationality = 'Nigerian'
let religion = 'Christian'
let occupation = 'beginner mobible app developer'
let ismarried = 'false'
let isselfemployed = 'true'
console.log= 'my name is'(firstnmae + surname + age + bill + favouritecolor + occupation)